id: IEC5EF444
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:11:58+00:00'
last_modified: '2022-06-08T09:54:07.398602+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10496
  title: སྨྱུང་གནས་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    68E5:
      image_group_id: I1KG12443
      title: Volume 1 of smyung gnas bla ma brgyud pa'i rnam thar/
      total_pages: 220
      order: 1
      base_file: 68E5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
