id: P006990
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10496
  title: སྨྱུང་གནས་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    7a236d7e05c641f9b8190c458092e464:
      image_group_id: I1KG12443
      title: ''
      volume_number: 1
      total_pages: 220
ebook_metadata:
  title: སྨྱུང་གནས་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར།
  author: ''
  sku: P006990
  cover: cover.jpg
  layers:
  - pagination
