id: P006990
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG10496
  title: སྨྱུང་གནས་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    996f7f8d2c7d41b898500ee4b54b6b58:
      image_group_id: I1KG12443
      title: Volume 1 of smyung gnas bla ma brgyud pa'i rnam thar/
      volume_number: 1
      total_pages: 220
      base_file: v001.txt
